# Generated by Django 2.2 on 2020-02-02 13:17

import AcceptPaymentApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=254)),
                ("first_name", models.CharField(max_length=254)),
                ("last_name", models.CharField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "currency",
                    models.CharField(
                        choices=[("EGP", "EGP"), ("$", "$")], max_length=12
                    ),
                ),
                ("total", models.FloatField(default=0)),
                ("date_issued", models.DateTimeField(default=services.helpers.dateNow)),
                ("date_of_payment", models.DateTimeField(blank=True, null=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "slug",
                    models.CharField(default=uuid.uuid4, max_length=200, unique=True),
                ),
                (
                    "end_date",
                    models.DateField(default=AcceptPaymentApp.models.plus4weeks_time),
                ),
                (
                    "order_id",
                    models.CharField(
                        default=services.helpers.rand_int, max_length=100, unique=True
                    ),
                ),
                ("payment_key", models.TextField(blank=True, null=True)),
                ("reason_for_failure", models.TextField(blank=True, null=True)),
                ("failure_response", models.TextField(blank=True, null=True)),
                ("downpayment", models.TextField(blank=True, null=True)),
                ("valu", models.BooleanField(default=False)),
                ("receipt_url_valu", models.TextField(blank=True, null=True)),
                (
                    "Subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paymob_payment",
                        to="app.Package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_payment_user",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
