# Generated by Django 2.2.6 on 2020-02-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcceptPaymentApp', '0003_payment_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_in_branch',
            field=models.BooleanField(default=False),
        ),
    ]
