# Generated by Django 2.2.6 on 2020-02-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcceptPaymentApp', '0004_payment_pay_in_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Subscription',
        ),
    ]
