# Generated by Django 2.2.6 on 2020-02-16 15:43

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('AcceptPaymentApp', '0006_payment_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=100, unique=True),
        ),
    ]
