"""
Django settings for tfg project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
from decouple import config

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
AUTH_USER_MODEL = "app.User"
SILENCED_SYSTEM_CHECKS = ["mysql.E001"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "app",
    "AcceptPaymentApp",
    "corsheaders",
    "coachapp",
]

# corsheaders

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tfg.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tfg.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "tfg",
        "USER": config("DATABASE_USER"),
        "PASSWORD": config("DATABASE_PASSWORD"),
        "HOST": config("DATABASE_URL"),
        "PORT": config("DATABASE_PORT"),
    }
}

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "services.paginator.CustomPagination",
    "PAGE_SIZE": 10,
}
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"


"""
    AWS related stuff
"""

AWS_HEADERS = {
    "Expires": "Thu, 31 Dec 2099 20:00:00 GMT",
    "Cache-Control": "max-age=94608000",
}

DEFAULT_FILE_STORAGE = "tfg.s3utils.MediaS3BotoStorage"
STATICFILES_STORAGE = "tfg.s3utils.StaticS3BotoStorage"
AWS_QUERYSTRING_AUTH = False
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = "gazef"
AWS_CLOUDFRONT_DOMAIN = "cdn.bit68.com"

S3_URL = "http://%s.s3.amazonaws.com" % AWS_STORAGE_BUCKET_NAME
STATIC_DIRECTORY = "/tfg/static/"
MEDIA_DIRECTORY = "/tfg/media/"
STATIC_URL = "http://cdn.bit68.com" + STATIC_DIRECTORY
MEDIA_URL = "http://cdn.bit68.com" + MEDIA_DIRECTORY

""" Online Payment """
ACCEPT_CONF = {
    "API_KEY": config("Accept_API_KEY"),
    "FRONTEND_URL": config("Accept_FRONTEND_URL"),
    "IFRAME_URL": config("Accept_IFRAME_URL"),
    "IFRAME_ID": config("Accept_IFRAME_ID"),
    "EGP_CARDINTEGRATIONID": config("Accept_EGP_CARDINTEGRATIONID"),
}
