# Generated by Django 2.2.6 on 2020-02-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachapp', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
#        migrations.AddField(
 #           model_name='user',
  #          name='coach_notes',
   #         field=models.ManyToManyField(blank=True, null=True, to='coachapp.CoachNote'),
    #    ),
        migrations.AlterField(
            model_name='user',
            name='SecondName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
