# Generated by Django 2.2.6 on 2020-02-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200209_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='period',
            field=models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], default='Month', max_length=200),
        ),
    ]
