# Generated by Django 2.2.6 on 2020-02-13 13:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200210_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttendanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_attendance_coach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session_class',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_bronze',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_gold',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_silver',
        ),
        migrations.RemoveField(
            model_name='session',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='session',
            name='current_seats',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='max_seats',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='users',
        ),
        migrations.AddField(
            model_name='attendance',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Package_attendance', to='app.Package'),
        ),
        migrations.AddField(
            model_name='package',
            name='deactivated_users',
            field=models.ManyToManyField(blank=True, related_name='deactivated_users_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='active_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SessionClass',
        ),
        migrations.AddField(
            model_name='sessionattendancerequest',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_date', to='app.SessionDates'),
        ),
        migrations.AddField(
            model_name='sessionattendancerequest',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package', to='app.Package'),
        ),
        migrations.AddField(
            model_name='sessionattendancerequest',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_session', to='app.Session'),
        ),
        migrations.AddField(
            model_name='sessionattendancerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='_SessionComments', to='app.SessionComments'),
        ),
        migrations.AddField(
            model_name='session',
            name='dates',
            field=models.ManyToManyField(blank=True, related_name='_SessionDates', to='app.SessionDates'),
        ),
    ]
