# Generated by Django 2.2.6 on 2020-02-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200213_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('info_type', models.CharField(choices=[('About', 'About'), ('Rules', 'Rules'), ('FAQ', 'FAQ')], max_length=20)),
            ],
        ),
    ]
