# Generated by Django 2.2.6 on 2020-02-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_generalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattendancerequest',
            name='joined',
            field=models.BooleanField(default=True),
        ),
    ]
