# Generated by Django 2.2.6 on 2020-02-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200217_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='period',
            field=models.CharField(choices=[('Month', 'Month'), ('3months', '3months'), ('endless', 'endless')], default='Month', max_length=200),
        ),
    ]
