# Generated by Django 2.2.6 on 2020-09-22 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200224_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SessionAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='session',
            name='dates',
        ),
        migrations.AddField(
            model_name='schedule',
            name='test',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='SecondName',
            field=models.CharField(blank=True, default='no_last_name', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='day',
            field=models.ManyToManyField(to='app.SessionDay'),
        ),
        migrations.AddField(
            model_name='session',
            name='difficulty_level',
            field=models.ManyToManyField(to='app.DifficultyLevel'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_at',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.SessionAt'),
        ),
    ]
