# Generated by Django 2.2.6 on 2020-09-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200922_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='month',
            field=models.ManyToManyField(to='app.SessionMonth'),
        ),
    ]
