# Generated by Django 2.2.6 on 2020-09-22 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachnote',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to=settings.AUTH_USER_MODEL),
        ),
    ]
